#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (c) 20121 astrorafael@gmail.com.
#
# See the LICENSE file for details
# ----------------------------------------------------------------------

python3 -m clicktrack "$@"
